const Angular = [
  "angular/overview",
  "angular/Introduction",
  "angular/AccessingServerOverHTTP",
  "angular/angular_material",
  "angular/ComponentsAndTemplates",
  "angular/DependencyInjection",
  "angular/FormsForUserInput",
  "angular/generating_mockdata_using_facker",
  "angular/NgModules",
  "angular/ObservableAndRxjs",
  "angular/Others",
  "angular/others_angular",
  "angular/project_file_structure",
  "angular/RoutingAndNavigation",
  "angular/typescript",
];

const C_Language = [
  "c_language/overview",
  "c_language/01intro",
  "c_language/02devenv",
  "c_language/03variables",
  "c_language/04operators",
  "c_language/05Example1",
  "c_language/06controlstatements",
  "c_language/07looping",
  "c_language/08functions",
  "c_language/09array",
  "c_language/10pointers",
  "c_language/11strings",
  "c_language/12structures",
  "c_language/13unions",
  "c_language/14files",
];

const Django = [
  "django/overview",
  "django/django_introduction",
  "django/django_template_engine",
  "django/django_saving_data_to_db",
  "django/django_authentication_authorization",
  "django/django_other",
];

const ML_DL = [
  "ml_dl/overview",
  "ml_dl/dl_intro",
  "ml_dl/intro_ai",
  "ml_dl/matplotlib",
  "ml_dl/ml_intro",
  "ml_dl/numpy",
  "ml_dl/pandas",
];

const NodeJS = [
  "nodejs/overview",
  "nodejs/nodejs_introduction",
  "nodejs/nodejs_builtin_modules",
  "nodejs/nodejs_module_system",
  "nodejs/npm_introduction",
  "nodejs/nodejs_mongodb",
  "nodejs/expressjs_introduction",
  "nodejs/expressjs_template_engine_ejs",
  "nodejs/expressjs_template_engine_pug",
  "nodejs/expressjs_getting_data_from_client",
  "nodejs/data_validation_using_joi",
  "nodejs/file_upload_using_multer",
  "nodejs/saving_data_to_db_using_mongoose",
  "nodejs/authentication_and_authorization",
  "nodejs/sending_mail_using_nodemailer",
  "nodejs/mvc_architecture",
  "nodejs/making_rest_api",
  "nodejs/other",
];

const Python = [
  "python/overview",
  "python/builtin_modules/builtin_modules",
  "python/builtin_modules/datetime",
  "python/builtin_modules/json",
  "python/builtin_modules/logging",
  "python/builtin_modules/py_testing",
  "python/builtin_modules/re",
  "python/builtin_modules/tkinter",
  "python/files/async_await",
  "python/files/builtin_functions",
  "python/files/iterator_generator",
  "python/files/operators",
  "python/files/others_datatypes",
  "python/files/pep",
  "python/files/string_formatting",
  "python/files/tasks",
  "python/pdbc/pdbc_mysql",
  "python/pdbc/pdbc_sqlite",
  "python/pdbc/unit_12",
  "python/Python Introduction",
  "python/Unit - 1",
  "python/unit_10",
  "python/unit_11",
  "python/unit_2",
  "python/unit_3",
  "python/unit_4",
  "python/unit_5",
  "python/unit_6",
  "python/unit_7",
  "python/unit_8",
  "python/unit_9",
];

const React = [
  "react/overview",
  "react/codeevolution_course-1",
  "react/codeevolution_course-2",
  "react/codeevolution_course-3",
  "react/mosh_course",
];

const Tools = [
  "tools/overview",
  "tools/cmd",
  "tools/git_github",
  "tools/heroku",
  "tools/markdown_introduction",
  "tools/others",
  "tools/screen_utility_linux",
  "tools/Shortcut_Sublime",
  "tools/Shortcut_VSCode",
  "tools/tools",
  "tools/vim",
];

const Web = [
  "web/overview",
  "web/bom_1",
  "web/bom_2",
  "web/css",
  "web/html",
  "web/introduction",
  "web/jquery",
  "web/js_core/basic_structure",
  "web/js_core/closures",
  "web/js_core/data_types",
  "web/js_core/ES6",
  "web/js_core/exception_handling",
  "web/js_core/flow_control_statements",
  "web/js_core/functions",
  "web/js_core/inheritance",
  "web/js_core/object",
  "web/js_core/ObjectDemo",
  "web/js_core/ObjectsMethods",
  "web/js_core/operaors",
  "web/js_core/others",
  "web/js_core/prototype_demo",
  "web/js_core/questions/10DaysOfJavaScript",
  "web/js_core/questions/questions",
  "web/js_core/README",
  "web/js_core/regex",
  "web/js_core/variable_scope",
  "web/pug_introduction",
  "web/sass_introduction",
];

module.exports = {
  docs: {
    Angular,
    C_Language,
    Django,
    ML_DL,
    NodeJS,
    Python,
    React,
    Tools,
    Web,
  },
};
