module.exports = {
  docs: {
    React: ["react/home", "react/introduction"],
    Angular: [
      "angular/home",
      "angular/Introduction",
      "angular/AccessingServerOverHTTP",
      "angular/angular_material",
      "angular/ComponentsAndTemplates",
      "angular/DependencyInjection",
      "angular/FormsForUserInput",
      "angular/generating_mockdata_using_facker",
      "angular/NgModules",
      "angular/ObservableAndRxjs",
      "angular/Others",
      "angular/others_angular",
      "angular/project_file_structure",
      "angular/RoutingAndNavigation",
      "angular/typescript",
    ],
    Django: [
      "django/home",
      "django/django_authentication_authorization",
      "django/django_introduction",
      "django/django_other",
      "django/django_saving_data_to_db",
      "django/django_template_engine",
    ],
    Python: [],
    NodeJS: [
      "nodejs/authentication_and_authorization",
      "nodejs/data_validation_using_joi",
      "nodejs/expressjs_getting_data_from_client",
      "nodejs/expressjs_introduction",
      "nodejs/expressjs_template_engine_ejs",
      "nodejs/expressjs_template_engine_pug",
      "nodejs/file_upload_using_multer",
      "nodejs/making_rest_api",
      "nodejs/mvc_architecture",
      "nodejs/nodejs_builtin_modules",
      "nodejs/nodejs_introduction",
      "nodejs/nodejs_module_system",
      "nodejs/nodejs_mongodb",
      "nodejs/npm_introduction",
      "nodejs/other",
      "nodejs/saving_data_to_db_using_mongoose",
      "nodejs/sending_mail_using_nodemailer",
    ],
  },
};
