module.exports = {
  docs: {
    React: [
      "react/home",
      "react/introduction",
      "react/codeevolution_course-1",
      "react/codeevolution_course-2",
      "react/codeevolution_course-3",
      "react/mosh_course",
    ],
    Angular: [
      "angular/home",
      "angular/Introduction",
      "angular/AccessingServerOverHTTP",
      "angular/angular_material",
      "angular/ComponentsAndTemplates",
      "angular/DependencyInjection",
      "angular/FormsForUserInput",
      "angular/generating_mockdata_using_facker",
      "angular/NgModules",
      "angular/ObservableAndRxjs",
      "angular/Others",
      "angular/others_angular",
      "angular/project_file_structure",
      "angular/RoutingAndNavigation",
      "angular/typescript",
    ],
    Django: [
      "django/home",
      "django/django_authentication_authorization",
      "django/django_introduction",
      "django/django_other",
      "django/django_saving_data_to_db",
      "django/django_template_engine",
    ],
    Python: [
      "python/builtin_modules/builtin_modules",
      "python/builtin_modules/datetime",
      "python/builtin_modules/json",
      "python/builtin_modules/logging",
      "python/builtin_modules/py_testing",
      "python/builtin_modules/re",
      "python/builtin_modules/tkinter",
      "python/files/async_await",
      "python/files/builtin_functions",
      "python/files/iterator_generator",
      "python/files/operators",
      "python/files/others_datatypes",
      "python/files/pep",
      "python/files/string_formatting",
      "python/files/tasks",
      "python/pdbc/pdbc_mysql",
      "python/pdbc/pdbc_sqlite",
      "python/pdbc/unit_12",
      "python/Python Introduction",
      "python/Unit - 1",
      "python/unit_10",
      "python/unit_11",
      "python/unit_2",
      "python/unit_3",
      "python/unit_4",
      "python/unit_5",
      "python/unit_6",
      "python/unit_7",
      "python/unit_8",
      "python/unit_9",
    ],
    NodeJS: [
      "nodejs/authentication_and_authorization",
      "nodejs/data_validation_using_joi",
      "nodejs/expressjs_getting_data_from_client",
      "nodejs/expressjs_introduction",
      "nodejs/expressjs_template_engine_ejs",
      "nodejs/expressjs_template_engine_pug",
      "nodejs/file_upload_using_multer",
      "nodejs/making_rest_api",
      "nodejs/mvc_architecture",
      "nodejs/nodejs_builtin_modules",
      "nodejs/nodejs_introduction",
      "nodejs/nodejs_module_system",
      "nodejs/nodejs_mongodb",
      "nodejs/npm_introduction",
      "nodejs/other",
      "nodejs/saving_data_to_db_using_mongoose",
      "nodejs/sending_mail_using_nodemailer",
    ],
    Tools: [
      'tools/cmd',
      'tools/git_github',
      'tools/heroku',
      'tools/markdown_introduction',
      'tools/others',
      'tools/screen_utility_linux',
      'tools/Shortcut_Sublime',
      'tools/Shortcut_VSCode',
      'tools/tools',
      'tools/vim'
    ]
  },
};
