const Angular = [
  "angular/overview",
  "angular/Introduction",
  "angular/AccessingServerOverHTTP",
  "angular/angular_material",
  "angular/ComponentsAndTemplates",
  "angular/DependencyInjection",
  "angular/FormsForUserInput",
  "angular/generating_mockdata_using_facker",
  "angular/NgModules",
  "angular/ObservableAndRxjs",
  "angular/Others",
  "angular/others_angular",
  "angular/project_file_structure",
  "angular/RoutingAndNavigation",
  "angular/typescript",
];

const C_Language = [
  "c_language/overview",
  "c_language/01intro",
  "c_language/02devenv",
  "c_language/03variables",
  "c_language/04operators",
  "c_language/05Example1",
  "c_language/06controlstatements",
  "c_language/07looping",
  "c_language/08functions",
  "c_language/09array",
  "c_language/10pointers",
  "c_language/11strings",
  "c_language/12structures",
  "c_language/13unions",
  "c_language/14files",
];

const Django = [
  "django/overview",
  "django/django_introduction",
  "django/django_template_engine",
  "django/django_saving_data_to_db",
  "django/django_authentication_authorization",
  "django/django_modal_fields",
  "django/django_other",
  "django/drf_random",
];

const ML_DL = [
  "ml_dl/overview",
  "ml_dl/dl_intro",
  "ml_dl/intro_ai",
  "ml_dl/matplotlib",
  "ml_dl/ml_intro",
  "ml_dl/numpy",
  "ml_dl/pandas",
];

const NodeJS = [
  "nodejs/overview",
  "nodejs/nodejs_introduction",
  "nodejs/nodejs_builtin_modules",
  "nodejs/nodejs_module_system",
  "nodejs/npm_introduction",
  "nodejs/nodejs_mongodb",
  "nodejs/expressjs_introduction",
  "nodejs/expressjs_template_engine_ejs",
  "nodejs/expressjs_template_engine_pug",
  "nodejs/expressjs_getting_data_from_client",
  "nodejs/data_validation_using_joi",
  "nodejs/file_upload_using_multer",
  "nodejs/saving_data_to_db_using_mongoose",
  "nodejs/authentication_and_authorization",
  "nodejs/sending_mail_using_nodemailer",
  "nodejs/mvc_architecture",
  "nodejs/making_rest_api",
  "nodejs/other",
];

const Python = [
  "python/overview",
  "python/builtin_modules/builtin_modules",
  "python/builtin_modules/datetime",
  "python/builtin_modules/json",
  "python/builtin_modules/logging",
  "python/builtin_modules/py_testing",
  "python/builtin_modules/re",
  "python/builtin_modules/tkinter",
  "python/files/async_await",
  "python/files/builtin_functions",
  "python/files/iterator_generator",
  "python/files/operators",
  "python/files/others_datatypes",
  "python/files/pep",
  "python/files/string_formatting",
  "python/files/tasks",
  "python/pdbc/pdbc_mysql",
  "python/pdbc/pdbc_sqlite",
  "python/pdbc/unit_12",
  "python/Python Introduction",
  "python/Unit - 1",
  "python/unit_10",
  "python/unit_11",
  "python/unit_2",
  "python/unit_3",
  "python/unit_4",
  "python/unit_5",
  "python/unit_6",
  "python/unit_7",
  "python/unit_8",
  "python/unit_9",
];

const React = [
  "react/overview",
  "react/codeevolution_course-1",
  "react/codeevolution_course-2",
  "react/codeevolution_course-3",
  "react/mosh_course",
];

const Tools = [
  "tools/overview",
  "tools/git_github_introduction",
  "tools/shortcuts_sublime_vscode",
  "tools/others",
];

const Web = [
  "web/introduction",
  "web/html",
  "web/pug_sass_jquery",
  "web/bom",
  "web/js_basic_structure",
  "web/js_data_types_operators",
  "web/js_flow_control_statements",
  "web/js_functions_inheritance",
  "web/js_scope_prototype",
  "web/js_exception_closure",
  "web/js_objects",
  "web/js_others",
  "web/js_es6",
];

module.exports = {
  docs: {
    Tools,
    Web,
    React,
    Angular,
    C_Language,
    Django,
    NodeJS,
    Python,
    ML_DL,
  },
};
